spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# =========================
# USER SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**


# =========================
# TRANSACTION SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[1].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/transactions/**


# =========================
# AI SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[2].id=ai-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://AI-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/ai/**


# =========================
# ANALYTICS SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[3].id=analytics-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/analytics/**


# =========================
# BEHAVIOR SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[4].id=behavior-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://BEHAVIOR-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/behavior/**


# =========================
# NOTIFICATION SERVICE
# =========================
spring.cloud.gateway.server.webmvc.routes[5].id=notification-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/notifications/**