spring.application.name=ai-service

server.port=8082

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/interactions
gemini.api.key=${GEMINI_API_KEY}

grok.api.url=https://api.groq.com/openai/v1/chat/completions
grok.api.key=${GROK_API_KEY}
grok.model=openai/gpt-oss-20b

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true