spring.application.name=behavior-service

server.port=8085



jwt.secret=SpendSenseJwtSecretKeyForDevelopmentOnly123456

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
